#!/bin/bash

 xrandr				\
 	--output HDMI-1-0	\
 	--primary		\
 	--mode 2560x1440	\
 	--rate 143		\
 	--above eDP1		\
 	--output eDP1		\
 	--mode 2560x1440	\
 	--rate 160		\

# xrandr				\
# 	--output HDMI-1-0	\
# 	--scale	1.3x1.3		\
# 	--auto			\
# 	--pos 0x0		\
# 	--primary		\
# 	--rate 143.97		\
# 	--output eDP1		\
# 	--scale 1x1		\
# 	--auto			\
# 	--pos 0x1872			# Scale * windowHeight

/usr/local/bin/dual_workspace
nitrogen --restore
