#!/bin/bash

FILE=/home/edjubert/.screenlayout/dual_monitor.sh
MONITOR="HDMI-1-0"
CHECK=`xrandr | grep "$MONITOR connected" | wc -l`

if [ -f "$FILE" ] && [ $CHECK -eq 1 ]; then
  sh $FILE

  echo "dual" > /home/edjubert/.config/i3/.monitor_preference
  /usr/local/bin/dual_workspace

  # nitrogen --restore
else
  echo "internal" > /home/edjubert/.config/i3/.monitor_preference
  /usr/local/bin/internal_monitor
fi

