#!/bin/bash

i3-msg workspace "1, move workspace to output HDMI-1-0"
i3-msg workspace "2, move workspace to output HDMI-1-0"
i3-msg workspace "3, move workspace to output HDMI-1-0"
i3-msg workspace "4, move workspace to output HDMI-1-0"
i3-msg workspace "5, move workspace to output HDMI-1-0"
i3-msg workspace "6, move workspace to output eDP-1"
i3-msg workspace "7, move workspace to output eDP-1"
i3-msg workspace "8, move workspace to output eDP-1"
i3-msg workspace "9, move workspace to output eDP-1"
i3-msg workspace "10, move workspace to output eDP-1"


/home/edjubert/.config/i3/generate_config dual
i3-msg restart
