#!/bin/bash

xrandr				\
	--output HDMI-1-0	\
	--mode 2560x1440	\
	--primary		\
	--rate 143.97		\
	--scale 1x1		\
	--auto			\
	--output eDP1 --off

/usr/local/bin/external_workspace
nitrogen --restore
