#!/bin/bash

FILE=/home/edjubert/.screenlayout/external_monitor.sh

if [ -f "$FILE" ]; then
  sh $FILE

  echo "external" > /home/edjubert/.config/i3/.monitor_preference
  /usr/local/bin/external_workspace
  # nitrogen --restore
else
  echo "internal" > /home/edjubert/.config/i3/.monitor_preference
  /usr/local/bin/internal_monitor
fi

