#!/bin/bash

FILE=/home/edjubert/.screenlayout/internal_monitor.sh

INTERNAL="eDP-1"
CHECK=`xrandr | grep "$INTERNAL connected" | wc -l`

if [ -f "$FILE" ] && [ $CHECK -eq 1 ]; then
  sh $FILE

  echo "internal" > /home/edjubert/.config/i3/.monitor_preference
  /usr/local/bin/internal_workspace
  # nitrogen --restore
else
  xrandr --auto
fi

